lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
    url(r'^new$', views.NewListView.as_view(), name='new_list'),
    url(r'^(?P<pk>\d+)/$', views.ViewAndAddToList.as_view(), name='view_list'),
]

superlists/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from lists import views as list_views
from lists import urls  as list_urls

urlpatterns = [
    url(r'^$', list_views.HomePageView.as_view(), name='home'),
    url(r'^lists/', include(list_urls)),
]

lists/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class List(models.Model):

    def get_absolute_url(self):
        return reverse('view_list', kwargs={'pk': self.id})

class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

    def get_absolute_url(self):
    	return reverse('view_list', args=[self.list.id])

    def __str__(self):
        return self.text

    class Meta:
        unique_together = ('list', 'text')
        ordering = ('id',)

lists/forms.py
from django import forms
from django.core.exceptions import ValidationError
from lists.models import Item

EMPTY_ITEM_ERROR     = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"

class ItemForm(forms.ModelForm):
    
    def save(self, for_list):
        self.instance.list = for_list
        return super().save()

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(
                attrs={
                    'placeholder': 'Enter a to-do item',
                    'class': 'form-control input-lg'
                }
            )
        }
        error_messages= {
            'text': {'required': EMPTY_ITEM_ERROR}
        }

class ExistingListItemForm(ItemForm):
    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list
    
    def save(self):
        return super(ItemForm, self).save()

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

lists/views.py
from django.core.exceptions import ValidationError
from django.views.generic   import FormView, CreateView, DetailView
from django.shortcuts import render
from django.http      import HttpResponse
from django.shortcuts import render, redirect
from lists.models     import Item, List
from lists.forms      import ItemForm, ExistingListItemForm
# Create your views here.
class HomePageView(FormView):
    template_name = 'home.html'
    form_class    = ItemForm

class ViewAndAddToList(DetailView, CreateView):
    model         = List
    template_name = 'list.html'
    form_class    = ExistingListItemForm

    def get_form(self):
        self.object = self.get_object()
        return self.form_class(for_list=self.object, data=self.request.POST)

class NewListView(CreateView):
    form_class = ItemForm
    template_name = 'home.html'

    def form_valid(self, form):
        list_ = List.objects.create()
        form.save(for_list=list_)
        return redirect(list_)

def new_list(request):
    if request.POST:
        form = ItemForm(data=request.POST)
        if form.is_valid():
            list_ = List.objects.create()
            form.save(for_list=list_)
            return redirect(list_)
        else:
            return render(request, 'home.html', {'form': form})

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>To-Do lists</title>
	<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
	<link href="/static/base.css" rel="stylesheet" type="text/css">
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-offset-3 jumbotron">
				<div class="text-center">
					<h1>{% block header_text %} {% endblock %}</h1>
						<form method="POST" action="{% block form_action %}{% endblock form_action %}">
							{{ form.text }}
							{% csrf_token %}
							{% if form.errors %}
								<div class="form-group has-error">
									<span class="help-block">{{ form.text.errors }}</span>
								</div>
							{% endif %}
						</form>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				{% block table %}
				{% endblock %}
			</div>
		</div>
	</div>
	</body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock%}

{% block table %}
	<table id="id_list_table">
		{% for item in list.item_set.all %}
			<tr><td>{{ forloop.counter }} : {{ item.text }}</td></tr>
		{% endfor %}
	</table>
{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
	<table id="id_list_table" class="table">
	{% for item in list.item_set.all %}
		<tr><td>{{forloop.counter}}: {{item.text}}</td></tr>
	{% endfor %}
	</table>
{% endblock %}
</form>